[package]
name = "hash_sign_02"
version = "1.0.0"

[addresses]
HashSign="0xb1f4afa3ba948a570499706b00124653cf54627fcdc421de1517d98f2eeb41f8"
aptos_framework = "0x1"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }
